### ISSUE TITLE
Typo: Missing space in your profile's README.md file in 'communityrecodehive'

### ISSUE THREAD

**Issue by Soumyodeep-Das** [sanjay-kv/sanjay-kv#16]
![image](https://github.com/user-attachments/assets/0c38f0b7-bb48-4bfe-93ec-b6758b9dc3be)
 
In the 4th line as it can be seen that the **community** word and **recodehive** word are combined together, but it should be separated by a blank space.
Kindly assign this task to me, so that I can fix the typo ASAP.
Thank You..
@sanjay-kv

**Comment by sanjay-kv** [comment]
this is not included in the gssoc
